[package]
name = "learn-Rust"
version = "0.1.0"
authors = ["Alexander A.Rodin <rodin_aa@mail.ru>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.19"
